// <auto-generated />
namespace StudentApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SeedForDept_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedForDept_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202002261149219_SeedForDept_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
